config/routes.rb
Rails.application.routes.draw do
  root to: 'movies#index'

  post    :login_or_register, to: 'sessions#create'
  delete  :logout, to: 'sessions#destroy'

  resources :movies, only: [:create, :destroy]
  get 'share' => 'movies#new', as: :share_movie
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user

  validates :url, presence: true

  before_create :set_title_description

  def embed_url
    url.gsub('watch?v=', 'embed/')
  end

  private

  def set_title_description
    info = VideoInfo.new(url)
    self.title = info.title
    self.description = info.description
  end
end

app/models/reverse.rb
class Reverse
  attr_accessor :items

  def initialize
    @items = []
  end

  def add(val)
    return if check_exist(val)

    items << val
  end

  def remove(val)
    items.delete(val)
  end

  def check_exist(val)
    items.any? val
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'net/http'
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def logged_in?
    !current_user.nil?
  end
  helper_method :logged_in?
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_login!, except: :index

  def index
    @movies = Movie.order(id: :desc)
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = current_user.movies.build(movie_params)

    if @movie.save
      flash[:success] = 'Share successfully'
      alert_telegram(@movie)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @movie = current_user.movies.find(params[:id])
    @movie.destroy

    flash[:success] = 'Delete Successfully'
    redirect_to root_path, status: :ok
  end

  private

  def movie_params
    params.require(:movie).permit(:url)
  end

  def require_login!
    return if logged_in?

    flash[:notice] = 'Require login or register'
    redirect_to root_path
  end

  def alert_telegram(movie)
    message = "You have a new movie added. It called '#{movie.title}'"
    uri = URI("#{TELEGRAM_API_URL}/#{TELEGRAM_BOT_TOKEN}/sendMessage?chat_id=#{TELEGRAM_CHAT_ID}&text=#{message}")

    Net::HTTP.get(uri)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_initialize_by(username: user_params[:username])

    if @user.new_record?
      create_user
    else
      login_user
    end

    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Logout successfully'

    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def create_user
    @user.password = user_params[:password]
    if @user.save
      flash[:success] = 'Register successfully'
      session[:user_id] = @user.id
    else
      flash[:error] = "Fail to register: #{error_message}"
    end
  end

  def login_user
    if @user.authenticate(user_params[:password])
      flash[:success] = 'Login successfully'
      session[:user_id] = @user.id
    else
      flash[:error] = 'Fail to login'
    end
  end

  def error_message
    @user.errors.full_messages.join(', ')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_name(flash_type)
    case flash_type.to_sym
    when :error
      'danger'
    when :alert
      'warning'
    when :notice
      'info'
    else
      'success'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Funny Movies</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta charset='utf-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'shared/nav' %>
  <div class="container mt-5">
    <%= render 'shared/flash_message' %>
    <%= yield %>
  </div>
</body>

</html>

app/views/movies/_movie.html.erb
<div class="row mt-5">
  <div class="col-4">
    <div class="ratio ratio-16x9">
      <iframe class="embed-responsive-item" src="<%= movie.embed_url %>" allowfullscreen></iframe>
    </div>
  </div>
  <div class="col-8">
    <h5><%=movie.title%></h5>
    <p>Shared By: <%=movie.user.username%></p>

    <p>Description: </p>
    <p class="text-break"><%=movie.description.truncate(500)%></p>
    <% if current_user == movie.user %>
      <%= link_to "Delete", movie_path(movie),
        data: {
          method: :delete,
          confirm: "Are you sure you want to delete this?"
        }, class: 'btn btn-danger btn-sm m-2'%>
    <%end%>
  </div>
</div>

app/views/movies/index.html.erb
<%= render @movies%>

app/views/movies/new.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_for @movie, html: { class: "border mt-5"} do |f| %>
    <div class="form-group m-4">
      <div class="row">
        <div class="col-sm-3">
          <%= f.label :url, 'Youtube URL:', class: 'col-form-label' %>
        </div>
        <div class="col-sm-9">
          <%= f.text_field :url, class: 'form-control' %>
          <% if @movie.errors.any? %>
            <div class="invalid-feedback">
              <%= @movie.errors.full_messages.join(', ')%>
            </div>
          <%end%>
        </div>
      </div>
      <div class="row">
        <label for="share" class="col-sm-3"></label>
        <div class="col-sm-9 mt-3">
          <%= f.submit 'Share', class: 'btn btn-success w-100' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

app/views/shared/_flash_message.html.erb
<% flash.each do |type, msg| %>
<div class="alert alert-<%=alert_class_name(type)%> alert-dismissible fade show">
  <%= msg %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="<%=root_path%>">
      <i class="fas fa-home fa-2x"></i>
      <span>Funny Movies</span>
    </a>

    <% if logged_in? %>
    <div>
      <span class="navbar-text me-3">
        Welcome
        <span class="font-weight-bold"><%= current_user.username %></span>
      </span>

      <%= link_to 'Share a movie', share_movie_path, class: 'btn btn-outline-success my-2 my-sm-0 me-3' %>
      <%= link_to 'Logout', logout_path, class: 'btn btn-outline-danger my-2 my-sm-0', method: :delete, data: { confirm: 'Are you sure to logout?' } %>
    </div>
    <% else %>
    <%=form_for :user, url: login_or_register_path, html: {class: 'd-flex'} do |f| %>
    <%= f.text_field :username, class: 'form-control me-2', placeholder: 'username' %>
    <%= f.text_field :password, class: 'form-control me-2', placeholder: 'password'  %>
    <%= f.submit 'Login / Register', class: 'btn btn-outline-success my-2 my-sm-0' %>
    <%end%>
    <% end %>
  </div>
</nav>